package io.nexuspay.dispute.application.service;

import io.nexuspay.common.id.PrefixedId;
import io.nexuspay.dispute.application.port.out.DisputeRepository;
import io.nexuspay.dispute.application.port.out.EvidenceStoragePort;
import io.nexuspay.dispute.application.port.out.LedgerPort;
import io.nexuspay.dispute.domain.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.InputStream;
import java.time.Instant;
import java.util.List;
import java.util.Optional;

/**
 * Core service managing the dispute lifecycle and chargeback ledger integration.
 *
 * <p>Orchestrates state transitions, evidence collection, and the corresponding
 * double-entry ledger entries for each phase of the dispute.</p>
 *
 * <h3>Chargeback Ledger Entries</h3>
 * <ul>
 *   <li><b>OPENED</b>: DR chargeback_reserve, CR merchant_receivables (reserve funds)</li>
 *   <li><b>WON</b>: DR merchant_receivables, CR chargeback_reserve (reverse reservation)</li>
 *   <li><b>LOST</b>: DR chargeback_expense, CR chargeback_reserve (finalise loss)</li>
 * </ul>
 *
 * @since 0.2.4 (Sprint 2.4)
 */
@Service
public class DisputeLifecycleService {

    private static final Logger log = LoggerFactory.getLogger(DisputeLifecycleService.class);

    private final DisputeRepository disputeRepository;
    private final EvidenceStoragePort evidenceStorage;
    private final LedgerPort ledgerPort;

    public DisputeLifecycleService(DisputeRepository disputeRepository,
                                    EvidenceStoragePort evidenceStorage,
                                    LedgerPort ledgerPort) {
        this.disputeRepository = disputeRepository;
        this.evidenceStorage = evidenceStorage;
        this.ledgerPort = ledgerPort;
    }

    /**
     * Opens a new dispute, creates chargeback reserve ledger entry.
     *
     * <p>IDEMPOTENT on {@code (tenantId, externalDisputeId)} (SEC-BATCH-2 / SEC-01):
     * a PSP redelivery or a replayed webhook for an already-opened dispute is a
     * no-op — it returns the existing dispute WITHOUT minting a second dispute or
     * re-posting the chargeback reserve (the money-moving line below). This mirrors
     * the transition-guard precedent in {@link #expire} (post to the ledger only
     * when a real change occurred). The {@code uq_disputes_tenant_external} UNIQUE
     * constraint (Flyway V4026) is the in-transaction race backstop for two
     * concurrent first-deliveries; because it is enforced at COMMIT inside this
     * same {@code @Transactional} as the ledger posting, a rolled-back transaction
     * leaves no durable suppression mark and a legitimate retry stays
     * reprocessable (avoids the B-015 pre-commit-mark-vs-rollback defect).</p>
     */
    @Transactional
    public Dispute openDispute(String tenantId, String paymentId, String externalDisputeId,
                               String reasonCode, String reasonDescription,
                               long amount, String currency, String network,
                               Instant evidenceDueDate) {

        // Idempotency guard: a dispute is uniquely identified by (tenant,
        // externalDisputeId). On a replay, no-op and return the existing dispute
        // so the chargeback reserve is posted EXACTLY ONCE.
        if (externalDisputeId != null && !externalDisputeId.isBlank()) {
            Optional<Dispute> existing =
                    disputeRepository.findByTenantIdAndExternalDisputeId(tenantId, externalDisputeId);
            if (existing.isPresent()) {
                Dispute prior = existing.get();
                log.info("duplicate dispute.opened ignored: tenant={}, external_id={}, existing_dispute={}",
                        tenantId, externalDisputeId, prior.getId());
                return prior;
            }
        }

        Dispute dispute = Dispute.open(tenantId, paymentId, externalDisputeId,
                reasonCode, reasonDescription, amount, currency, network, evidenceDueDate);

        dispute = disputeRepository.save(dispute);

        // Persist all domain events generated by the factory
        for (DisputeEvent event : dispute.getEvents()) {
            disputeRepository.saveEvent(event);
        }

        // Create chargeback reserve in ledger under the dispute's server-authoritative
        // tenant (SEC-24) — the same tenantId used for the dispute idempotency key above.
        ledgerPort.createChargebackReserve(tenantId, dispute.getId(), amount, currency);

        log.info("Dispute opened: id={}, payment={}, amount={} {}, network={}",
                dispute.getId(), paymentId, amount, currency, network);

        return dispute;
    }

    /**
     * Transitions dispute to EVIDENCE_NEEDED.
     */
    @Transactional
    public Dispute requestEvidence(String disputeId, String actor) {
        Dispute dispute = getOrThrow(disputeId);
        int eventsBefore = dispute.getEvents().size();
        dispute.requestEvidence(actor);
        dispute = disputeRepository.save(dispute);
        saveNewEvents(dispute, eventsBefore);
        log.info("Evidence requested: dispute={}", disputeId);
        return dispute;
    }

    /**
     * Uploads evidence file and attaches it to the dispute.
     */
    @Transactional
    public DisputeEvidence uploadEvidence(String disputeId, String tenantId,
                                          DisputeEvidenceType type, String fileName,
                                          InputStream content, String contentType,
                                          String description) {

        Dispute dispute = getOrThrow(disputeId);

        // Store file in object storage
        String fileKey = evidenceStorage.store(tenantId, disputeId, fileName, content, contentType);

        DisputeEvidence evidence = new DisputeEvidence(
                PrefixedId.disputeEvidence(), disputeId, tenantId,
                type, fileKey, fileName, null, description
        );

        int eventsBefore = dispute.getEvents().size();
        dispute.addEvidence(evidence);
        disputeRepository.save(dispute);
        saveNewEvents(dispute, eventsBefore);

        evidence = disputeRepository.saveEvidence(evidence);

        log.info("Evidence uploaded: dispute={}, type={}, file={}",
                disputeId, type, fileName);

        return evidence;
    }

    /**
     * Submits collected evidence (marks dispute as EVIDENCE_SUBMITTED).
     */
    @Transactional
    public Dispute submitEvidence(String disputeId, String actor) {
        Dispute dispute = getOrThrow(disputeId);
        int eventsBefore = dispute.getEvents().size();
        dispute.submitEvidence(actor);
        dispute = disputeRepository.save(dispute);
        saveNewEvents(dispute, eventsBefore);
        log.info("Evidence submitted: dispute={}", disputeId);
        return dispute;
    }

    /**
     * Marks dispute as WON — reverses chargeback reserve.
     */
    @Transactional
    public Dispute win(String disputeId, String actor) {
        Dispute dispute = getOrThrow(disputeId);
        int eventsBefore = dispute.getEvents().size();
        dispute.win(actor);
        dispute = disputeRepository.save(dispute);
        saveNewEvents(dispute, eventsBefore);

        // Post under the dispute's persisted server-authoritative tenant (SEC-24) so
        // the reversal lands on the SAME tenant as the original reserve.
        ledgerPort.reverseChargebackReserve(dispute.getTenantId(), dispute.getId(),
                dispute.getAmount(), dispute.getCurrency());

        log.info("Dispute won: id={}, amount={} {}", disputeId, dispute.getAmount(), dispute.getCurrency());
        return dispute;
    }

    /**
     * Marks dispute as LOST — finalises chargeback as expense.
     */
    @Transactional
    public Dispute lose(String disputeId, String actor) {
        Dispute dispute = getOrThrow(disputeId);
        int eventsBefore = dispute.getEvents().size();
        dispute.lose(actor);
        dispute = disputeRepository.save(dispute);
        saveNewEvents(dispute, eventsBefore);

        // Post under the dispute's persisted server-authoritative tenant (SEC-24) so
        // the expense lands on the SAME tenant as the original reserve.
        ledgerPort.finaliseChargebackExpense(dispute.getTenantId(), dispute.getId(),
                dispute.getAmount(), dispute.getCurrency());

        log.info("Dispute lost: id={}, amount={} {}", disputeId, dispute.getAmount(), dispute.getCurrency());
        return dispute;
    }

    /**
     * Expires a dispute whose evidence deadline has passed.
     */
    @Transactional
    public Dispute expire(String disputeId) {
        Dispute dispute = getOrThrow(disputeId);
        int eventsBefore = dispute.getEvents().size();
        dispute.expire();
        // expire() is idempotent — it no-ops on an already-terminal dispute and
        // produces no new event. Post to the ledger ONLY when the transition
        // actually happened; otherwise a redundant dispute.expired webhook would
        // double-post the chargeback expense and drain the reserve twice.
        boolean transitioned = dispute.getEvents().size() > eventsBefore;
        dispute = disputeRepository.save(dispute);
        saveNewEvents(dispute, eventsBefore);

        if (transitioned) {
            // Lost by default — finalise chargeback under the dispute's persisted
            // server-authoritative tenant (SEC-24), matching the original reserve.
            ledgerPort.finaliseChargebackExpense(dispute.getTenantId(), dispute.getId(),
                    dispute.getAmount(), dispute.getCurrency());
            log.info("Dispute expired: id={}", disputeId);
        } else {
            log.info("Dispute {} already terminal, skipping ledger finalisation", disputeId);
        }
        return dispute;
    }

    // -- Query methods --

    public Optional<Dispute> findById(String id) {
        return disputeRepository.findById(id);
    }

    /**
     * Idempotency lookup used by the webhook handler to distinguish a first
     * delivery from a replay (so it can return {@code created} vs {@code duplicate}).
     */
    public Optional<Dispute> findByTenantIdAndExternalDisputeId(String tenantId, String externalDisputeId) {
        return disputeRepository.findByTenantIdAndExternalDisputeId(tenantId, externalDisputeId);
    }

    public List<Dispute> listByTenant(String tenantId, int limit, int offset) {
        return disputeRepository.findByTenant(tenantId, limit, offset);
    }

    public List<DisputeEvent> getTimeline(String disputeId) {
        return disputeRepository.findEventsByDisputeId(disputeId);
    }

    public List<DisputeEvidence> getEvidence(String disputeId) {
        return disputeRepository.findEvidenceByDisputeId(disputeId);
    }

    // -- Helpers --

    private Dispute getOrThrow(String disputeId) {
        return disputeRepository.findById(disputeId)
                .orElseThrow(() -> new IllegalArgumentException("Dispute not found: " + disputeId));
    }

    private void saveNewEvents(Dispute dispute, int eventsBefore) {
        List<DisputeEvent> allEvents = dispute.getEvents();
        for (int i = eventsBefore; i < allEvents.size(); i++) {
            disputeRepository.saveEvent(allEvents.get(i));
        }
    }
}
