apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nexuspay.fullname" . }}-config
data:
  KAFKA_REPLICATION_FACTOR: "{{ .Values.nexuspay.kafka.replicationFactor }}"
  KAFKA_PARTITIONS: "{{ .Values.nexuspay.kafka.partitions }}"
  RATE_LIMIT_MAX_REQUESTS: "{{ .Values.nexuspay.rateLimit.maxRequests }}"
  RATE_LIMIT_WINDOW_SECONDS: "{{ .Values.nexuspay.rateLimit.windowSeconds }}"
