apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexuspay.fullname" . }}-secret
type: Opaque
stringData:
  db-username: {{ .Values.nexuspay.database.username }}
  db-password: {{ .Values.nexuspay.database.password }}
  hyperswitch-api-key: {{ .Values.nexuspay.hyperswitch.apiKey | default "dev_api_key" }}
  hyperswitch-webhook-secret: {{ .Values.nexuspay.hyperswitch.webhookSecret | default "dev_webhook_secret" }}
